apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
type: Opaque

stringData:
  root-password: my-secret-pw
  auth-password: my-secret-pw
  auth-user: authuser