name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - auth
          - weather
          - ui

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: husseinbadran/${{ matrix.app }}
      
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV


      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.app }}
          push: true
          tags: |
            husseinbadran/${{ matrix.app }}:latest
            husseinbadran/${{ matrix.app }}:${{ env.SHORT_SHA }}

      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: husseinbadran/${{ matrix.app }}:.*|image: husseinbadran/${{ matrix.app }}:${SHORT_SHA}|g" \
          base/kubernetes/${{ matrix.app }}/deployment.yaml

      - name: Commit updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add base/kubernetes

          if git diff --cached --quiet; then
            echo "Nothing changed."
            exit 0
          fi

          git commit -m "Update images to ${SHORT_SHA}"
          git push      