name: Trivy Image Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - auth
          - ui
  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ matrix.app }}:latest \
            ./${{ matrix.app }}

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ matrix.app }}:latest
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
          ignore-unfixed: true
